In [1]:
import numpy as np

In [2]:
# Creating a Matrix using numpy

matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [4]:
matrix_2.shape 

(3, 3)

In [5]:
# Creating Matrices with Random Values

random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.80729437 0.2812881  0.16949019]
 [0.75940814 0.3349038  0.00195099]
 [0.57225166 0.20831996 0.45688722]]


In [6]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))

print(random_integer_matrix)


[[13  6  0 33 44]
 [ 0 46 29 43 80]
 [54 69 29 53 54]
 [53 49 46 40  7]]


In [8]:
# Matrix with all the values as 1

matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [12]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [13]:
#Null Matrix or Zero Matrix

null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# Identity Matrix
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
